### PR TITLE
fix: #333 made the studio step two header, mobile friendly

### PR DESCRIPTION
**Pull request by deltork**
### PR Goal? 
fix a bug

### Fixes? 
#333

### Feedback sought? 
sanity check

### Priority? 
high

### Tests added? 
n/a

### How to test? 
use the browser device emulator on the PR preview

### Confidence? 
very

### Version change? 
patch

### CODE REVIEW

**Comment by dhdaines** [comment]
Hmm. Doesn't seem to be very iPad friendly (let alone phone friendly) according to Chrome's dev tools:
image

**Comment by deltork** [comment]
> Hmm. Doesn't seem to be very iPad friendly (let alone phone friendly) according to Chrome's dev tools: image

this is what it looks like Chrome dev tools on windows 11:
image


this is what is looks like Edge dev tools on windows 11: 
image

**Comment by dhdaines** [comment]
Hmm, maybe I'm not picking up the right version from the dev preview?  I'll try rebuilding locally to see.

**Comment by deltork** [comment]
> Hmm, maybe I'm not picking up the right version from the dev preview? I'll try rebuilding locally to see.

It might be, I used the PR preview https://readalong-studio.mothertongues.org/pr-preview/pr-334/#/ for my screenshot 
image

**Comment by dhdaines** [comment]
I think there's just something weird going on with responsive design mode on my Chrome, because it looks fine in a normal window when I resize it...

**Comment by joanise** [comment]
This looks quite good to me, thanks! On a small screen, the download button ends up taking more real estate that I hoped.

I imagined it shrinking the format list, rather than wrapping it, something like a little triangle that when you clicked on it, it expanded the list, but otherwise you'd see just this triangle left of the download arrow if there's no space for the long drop down.

But I'm scope creeping here, I'm happy to approve as is as well.

**Review by joanise — APPROVED** [review]
lgtm

**Pull request merged**
