### PR TITLE
feat: connect studio tour to editor tour

### PR DESCRIPTION
**Pull request by deltork**
### PR Goal? 
Connecting studio tour to the editor tour

### Fixes? 
n/a

### Feedback sought? 
sanity check

### Priority? 
low

### Tests added? 
n/a

### How to test? 
Do the full tour in the pr preview

### Confidence? 
High

### Version change? 
patch

### CODE REVIEW

**Comment by joanise** [comment]
This is OK, but it would be nice to bring the user's attention up to the Editor button in the top-right corner. Can we have an extra step in the Studio tour on the Editor button, with something like:
Title: Go to the Editor
Text: Once you've downloaded your ReadAlong, you can reload it into the Editor to continue editing it.
Here you could have the Finish and Editor buttons to finish or continue on to the Editor tour.

**Comment by deltork** [comment]
@joanise, please add translations for fr and es.

**Comment by deltork** [comment]
Thanks

**Review by joanise — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
