### PR TITLE
fix(fr): create specific configs for serve and use --localize for deployment

### PR DESCRIPTION
**Pull request by roedoejet**
See https://github.com/nrwl/nx/issues/2839

### CODE REVIEW

**Comment by roedoejet** [comment]
@dhdaines - this is why the /fr/ endpoint isn't working (I think). In production, we replace the localhost:8000 endpoint with the actual RAS api, but for some reason (argh) nx silently fails to build if you specify more than one configuration (something that is perfectly valid in angular.json). So, as a hack, I've just copy/pasted the production configuration into the fr configuration. This could fix the issue assigned to you on clickup, but there might be a better way of doing it.

**Comment by dhdaines** [comment]
Thanks for the link!  There seem to be various workarounds possible - I'll play around with it a bit to see what our best option is.

**Review by dhdaines — APPROVED** [review]
I think it is better to be explicit about what we are doing when we build for deployment - instead of trying to mix configurations, we can just use --localize and explicit --deleteOutputPath=false, which says what we're doing - build a localized version inside the already-built default English one.

**Comment by dhdaines** [comment]
Note that for `serve` you can't pass `--localize` so in this case we just take the Cartesian product of configurations and languages, which is fine for the moment since we only have two languages.

**Comment by dhdaines** [comment]
Whoops, I re-broke API problem!  Will make another PR...

**Comment by dhdaines** [comment]
Oh, never mind, it's just GH pages deployment is slow (because Ruby).  It's fixed now!

**Pull request merged**
