### PR TITLE
Detect and report g2p warnings

### PR DESCRIPTION
**Pull request by dhdaines**
Gives a nice and helpful warning box with all the fallback/g2p failures in the log.  Note that:

- There could be a *lot* of warnings
- Not sure how to put line breaks between them (it doesn't seem possible, unfortunately)

### CODE REVIEW

**Review by joanise — APPROVED** [review]
This is super nice, thanks! I would made keep the message there longer than 15 seconds, though, if there are a lot of warnings, that's not longe enough to read them. I think 30 seconds would not be too long for this.

**Comment by dhdaines** [comment]
Sounds good, I'll put it up to 30 seconds and also go grep for other possible g2p errors it might report

**Comment by joanise** [comment]
Oops, I just pushed the 30s, I didn't read your reply soon enough.

**Comment by dhdaines** [comment]
No problem.  I think matching all lines in the log with "g2p" in them should get us everything relevant, based on my reading of the ReadAlongs code, so I think we can merge this now!

**Comment by joanise** [comment]
Good idea to get all the g2p errors. I see I should still generate an additional one when the final g2p for a word is empty, though. That's still the cause behind the alignment failure. But that's not a problem for this PR, which is ready to merge as far as I'm concerned.

**Pull request merged**
