### PR TITLE
feat: simplify language selection

### PR DESCRIPTION
**Pull request by roedoejet**

### CODE REVIEW

**Comment by joanise** [comment]
The English looks great, thanks!
Question, is it normal that when some strings are missing, trying to serve the Spanish or French interface just fails to compile? I get these error messages, which are really not saying to me "translate some missing strings"!
```
./packages/ngx-web-component/src/lib/ngx-web-component.module.ts:5:0-20 - Error: export 'defineCustomElements' (imported as 'defineCustomElements') was not found in '@readalongs/web-component/loader' (module has no exports)

./packages/studio-web/src/app/app.module.ts:19:0-20 - Error: export 'defineCustomElements' (imported as 'defineCustomElements') was not found in '@readalongs/web-component/loader' (module has no exports)
```

**Comment by joanise** [comment]
Bug: the Tour is broken in Step 2. Once I get to the second "Play your readalong" shepherd step, it just gives me a greyed out screen without the next step or any way to continue. I have to reload the whole page to recover.

**Comment by roedoejet** [comment]
> The English looks great, thanks! Question, is it normal that when some strings are missing, trying to serve the Spanish or French interface just fails to compile? I get these error messages, which are really not saying to me "translate some missing strings"!
> 
> ```
> ./packages/ngx-web-component/src/lib/ngx-web-component.module.ts:5:0-20 - Error: export 'defineCustomElements' (imported as 'defineCustomElements') was not found in '@readalongs/web-component/loader' (module has no exports)
> 
> ./packages/studio-web/src/app/app.module.ts:19:0-20 - Error: export 'defineCustomElements' (imported as 'defineCustomElements') was not found in '@readalongs/web-component/loader' (module has no exports)
> ```

No, I don't get that at all - this sounds like a problem with nx/the web component not being installed properly. I get these messages:

```
./packages/studio-web/src/app/shepherd.steps.ts - Warning: Module Warning (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
(Emitted value instead of an instance of Error) No translation found for "5598621379448184205" ("For most users, the default settings here are appropriate, and you don't need to do anything else - just keep this option selected!").

./packages/studio-web/src/app/shepherd.steps.ts - Warning: Module Warning (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
(Emitted value instead of an instance of Error) No translation found for "6215852496756629103" ("Then, optionally, you can select the language of your ReadAlong.").

./packages/studio-web/src/app/upload/upload.component.ts - Warning: Module Warning (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
(Emitted value instead of an instance of Error) No translation found for "3896053555277429649" ("Please select a language or choose the default option").

./packages/studio-web/src/app/upload/upload.component.ts - Warning: Module Warning (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
(Emitted value instead of an instance of Error) No translation found for "4382352341548079905" ("Select a specific language").

./packages/studio-web/src/app/upload/upload.component.ts - Warning: Module Warning (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
(Emitted value instead of an instance of Error) No translation found for "7273199130532280751" (" Optional: Change language settings ").
```

**Comment by roedoejet** [comment]
> Bug: the Tour is broken in Step 2. Once I get to the second "Play your readalong" shepherd step, it just gives me a greyed out screen without the next step or any way to continue. I have to reload the whole page to recover.

Weird. I'll look into this

**Comment by roedoejet** [comment]
@joanise - I think I fixed the tour issue here: [00e026e](https://github.com/ReadAlongs/Web-Component/pull/209/commits/00e026ebcd24ff569b50a87a87f8dc6a2a6b1c68) but I have no idea why it came up in this PR - it should have been an issue before too, but it appears to work on the [site](https://readalong-studio.mothertongues.org/)

**Comment by joanise** [comment]
> @joanise - I think I fixed the tour issue here: [00e026e](https://github.com/ReadAlongs/Web-Component/pull/209/commits/00e026ebcd24ff569b50a87a87f8dc6a2a6b1c68) but I have no idea why it came up in this PR - it should have been an issue before too, but it appears to work on the [site](https://readalong-studio.mothertongues.org/)

All I can say is that it works in `origin/main` but not in this branch. When I played with it, I did not understand why and why not, so I figured I'd just leave a note here. Glad you figured it out!

**Comment by joanise** [comment]
The first "Edit your ReadAlong" shepherd step is no longer attached to Title/Subtitle the way it used to be, did some element change name or id?

**Comment by roedoejet** [comment]
> The first "Edit your ReadAlong" shepherd step is no longer attached to Title/Subtitle the way it used to be, did some element change name or id?

It should be as of [00e026e](https://github.com/ReadAlongs/Web-Component/pull/209/commits/00e026ebcd24ff569b50a87a87f8dc6a2a6b1c68) - have you tried it since then?

**Comment by joanise** [comment]
> > The first "Edit your ReadAlong" shepherd step is no longer attached to Title/Subtitle the way it used to be, did some element change name or id?
> 
> It should be as of [00e026e](https://github.com/ReadAlongs/Web-Component/pull/209/commits/00e026ebcd24ff569b50a87a87f8dc6a2a6b1c68) - have you tried it since then?

I thought I had, but I must have been on the wrong branch when I tested, it works fine now.

**Comment by joanise** [comment]
Currently working on the French translation for this PR.

**Comment by joanise** [comment]
The contact us link embedded in the tour is also broken. It ends up trying to open `http://localhost:4200/%7B%7B%20contactLink%20%7D%7D` instead of the intended `mailto:` target.
I can fix it by hard-coding `<a href="mailto:readalong.studio@gmail.com">` in `shepherd.steps.ts` but it would of course be nicer to maintain the parameterization we had with the e-mail address coming ultimately from `package.json` as it does elsewhere.

**Comment by joanise** [comment]
I've now made some fixes on the English, a hack so I could spin up the es and fr interface on my machine again, and a complete draft of the French translations.
TODO:
 - Spanish translations
 - fix the contact link in the tour

**Comment by joanise** [comment]
And, a complete first draft of the Spanish translations is now in too.
@roedoejet can you check the contactLink in the shepherd tour, and ask for a review of the Spanish text?
@dhdaines I think you were willing to review my French text, that would be helpful please.

**Comment by joanise** [comment]
Doh, I fixed the messages for the fixed tour yesterday, but forgot to push. This PR now just needs native speaker review and can get merged.

**Review by joanise — APPROVED** [review]

**Pull request merged**
