### PR TITLE
Switch from .ras to .readalong as file extension

### PR DESCRIPTION
**Pull request by dhdaines**

### CODE REVIEW

**Review by joanise — CHANGES_REQUESTED** [review]
Mostly good, but needs i18n and FR l10n updates too.

**Comment by joanise** [comment]
PS: you edited the text of the messages in `i18n/*` but you also need to update the keys.

**Comment by joanise** [comment]
PPS: I'm fixing it for you, and I'm also going to add CI checks that i18n and l10n are up to date, so we find out faster.

**Comment by dhdaines** [comment]
> PS: you edited the text of the messages in `i18n/*` but you also need to update the keys.

Oh, what a pain!!!  I wonder why Angular i18n couldn't just work like good old gettext which has existed for 100 years and never had this problem.

**Review by dhdaines — COMMENTED** [review]
No idea how to confirm that the changes are made, I think you have to switch your review to "approve"!  Thanks for the updates!

**Review by joanise — APPROVED** [review]
This is ready to merge once CI passes.

**Pull request merged**
