### PR TITLE
Replace contact us by project page link

### PR DESCRIPTION
**Pull request by joanise**
Related to #124, but not quite fixing it yet.

I'd like the URL I'm linking to to come from package.json or project.json. I don't know how to do that, but I hope it's trivial for one of you.

### CODE REVIEW

**Comment by roedoejet** [comment]
the whole package.json is available from `environment` so you just `import { environment } from 'environments/environment'` (the folder is right next to i18n). In production the environment.ts file gets swapped out for environment.prod.ts so don't worry about pulling environment from there or anything

**Comment by joanise** [comment]
Fixed. Ready for re-review.

**Comment by joanise** [comment]
Oh wait, I put my variable definition in `environment.ts`, is that OK, or should I literally put it in `package.json`?

**Comment by joanise** [comment]
I think I mean it now. :)

**Review by dhdaines — CHANGES_REQUESTED** [review]
Hi! It needs the contact info updated on the error page too, otherwise looks good - perhaps with a link specifically to the issues page.

**Comment by joanise** [comment]
> Hi! It needs the contact info updated on the error page too, otherwise looks good - perhaps with a link specifically to the issues page.

Right, how about making "contact the developers" a link to that documentation page? I assume we'll eventually put contact information on there...

**Comment by joanise** [comment]
All right, version one million, I now use the new e-mail address Marc created and the contact links are mailto: links.

The documentationURL is still in the package.json, but not shown anywhere. Post ICLDC, we can fix that and have a real general documentation page.

**Review by dhdaines — APPROVED** [review]

**Pull request merged**
