### PR TITLE
fix(web-component): issue 108

### PR DESCRIPTION
**Pull request by roedoejet**

### CODE REVIEW

**Comment by roedoejet** [comment]
Functionality seems to be great, congratulations @deltork ! the git history is quite old (actually, only 8 days since 89dccada338e89b7b1705ab3e0449f6d021d5538, but there have been an eye-watering 162 commits since then)

I think we should wait for the Git Wizard @joanise to advise what to do here as trying to merge these presents a nasty merge conflict. After that, I vote that we approve this and release patch 1.0.1

**Comment by roedoejet** [comment]
I tried to merge here, but not sure if it's right: https://github.com/ReadAlongs/Web-Component/tree/dev.patch-issue-108-merge

**Comment by joanise** [comment]
This is awesome, Del, thanks for figuring out how to fix this jarring bug!

**Comment by joanise** [comment]
@roedoejet The merge you did was correct, but with such a long jump over the merge, I preferred to use a rebase instead.

The rebase and merge both had nasty conflicts because we applied prettier to the whole code base in `main` after the base of this PR.

My solution in these situations is to prettify the base, prettify the changed file, and create a new commit that applies the changes from the prettified based to the prettified changed file. That's something that can easily be applied onto `origin/main` with conflicts.

I did just that:
 - go to the parent commit `git checkout patch.issue-108^`
 - create a new branch `git switch -c dev.rebase-108`
 - run prettier on `read-along.tsx`
 - commit.  `git commit -a -m'chore: new base'` I will discard this commit shortly, but it will provide a base that is conflict free from which to apply Del's patch.
 - `git checkout patch.issue-108 packages/web-component/src/components/read-along-component/read-along.tsx`
 - run prettier on `read-along.tsx`
 - Commit that, preserving Del's author and date:
    - `git add packages/web-component/src/components/read-along-component/read-along.tsx`
    - `git commit --date "Fri Feb 24 18:27:14 2023 -0500" --author "Delasie Torkornoo <delasie.torkornoo@carleton.ca>" -m "fix(web-component): issue 108"`
 - go back to `patch.issue-108` and reset it to start at `origin/main`:
    - `git checkout patch.issue-108`
    - `git reset --hard origin/main`
 - and cherry pick Del's rewritten commit `git cherry-pick dev.rebase-108`
 - Test, validate by inspecting diffs, and force push once I was happy with my work: `git push -f origin patch.issue-108`

**Review by joanise — APPROVED** [review]
Looks good, nice fix, works on my computer.

**Comment by roedoejet** [comment]
> @roedoejet The merge you did was correct, but with such a long jump over the merge, I preferred to use a rebase instead.
> 
> The rebase and merge both had nasty conflicts because we applied prettier to the whole code base in `main` after the base of this PR.
> 
> My solution in these situations is to prettify the base, prettify the changed file, and create a new commit that applies the changes from the prettified based to the prettified changed file. That's something that can easily be applied onto `origin/main` with conflicts.
> 
> I did just that:
> 
> * go to the parent commit `git checkout patch.issue-108^`
> * create a new branch `git switch -c dev.rebase-108`
> * run prettier on `read-along.tsx`
> * commit.  `git commit -a -m'chore: new base'` I will discard this commit shortly, but it will provide a base that is conflict free from which to apply Del's patch.
> * `git checkout patch.issue-108 packages/web-component/src/components/read-along-component/read-along.tsx`
> * run prettier on `read-along.tsx`
> * Commit that, preserving Del's author and date:
>   
>   * `git add packages/web-component/src/components/read-along-component/read-along.tsx`
>   * `git commit --date "Fri Feb 24 18:27:14 2023 -0500" --author "Delasie Torkornoo <delasie.torkornoo@carleton.ca>" -m "fix(web-component): issue 108"`
> * go back to `patch.issue-108` and reset it to start at `origin/main`:
>   
>   * `git checkout patch.issue-108`
>   * `git reset --hard origin/main`
> * and cherry pick Del's rewritten commit `git cherry-pick dev.rebase-108`
> * Test, validate by inspecting diffs, and force push once I was happy with my work: `git push -f origin patch.issue-108`

Thanks so much for explaining all this @joanise ! sounds very reasonable

**Pull request merged**
