### PR TITLE
fix for issue 108

### LINKED ISSUE #108: "click" play    and  word is not in view   , interface will not focus
When you load a  long page RA   , if you were at the bottom of the text and click play for example.   The interface will not focus on the first  word highlighted and also the interface starts to  jumping around till it catches up.

### PR DESCRIPTION
**Pull request by deltork**
minor change to vertical behaviour scrolling 
Closes #108

### CODE REVIEW

**Comment by joanise** [comment]
Did you have a read-along I could test this with? 
Such a trivial code change in the end, TS troubleshooting can be so annoying sometimes!

**Comment by deltork** [comment]
> Did you have a read-along I could test this with? Such a trivial code change in the end, TS troubleshooting can be so annoying sometimes!
see ` ej-fra-long-text.readalong` in the `test-data` folder

**Review by joanise — APPROVED** [review]
Thanks, this does improve scrolling.

**Comment by joanise** [comment]
Please take a moment to rebase the branch onto main before merging, though.

**Comment by joanise** [comment]
I.e., 
```
git fetch
git checkout 108-bug-long-text-highlighting-and-scrolling
git rebase origin/main
```
then `git push -f origin 108-bug-long-text-highlighting-and-scrolling`

And maybe also squash all the commits into 1?

**Pull request merged**
